### PR TITLE
Fix date handling on Firefox for notes, and remove duplicates from notes page

### LINKED ISSUE #29: Add date picker to "add a note"

### PR DESCRIPTION
**Pull request by jheretic**
This replaces the standard material-ui date picker that doesn't render on Firefox with @material-ui/pickers, changes the notes page to use the `date` field instead of `updated_at`, and removes duplicates entries from the notes list. Fixes #29

### CODE REVIEW

File: src/frontend/components/utils/AddNote.jsx [hunk 1]
```diff
@@ -140,22 +122,17 @@ export default function AddNote(props) {
...
-            onChange={handleInputChange}
-            InputLabelProps={{
-              shrink: true,
-            }}
+
+        <MuiPickersUtilsProvider utils={DateFnUtils}>
+          <DateTimePicker
+            className={classes.datePicker}
+            value={date}
+            onChange={e => setDate(e.target.value)}
```
Comment (harumhelmy) [inline src/frontend/components/utils/AddNote.jsx:132]: Got a type error when I tested locally — `onChange={e => setDate(e)}` works!

File: src/frontend/components/utils/EditNote.jsx [hunk 2]
```diff
@@ -132,24 +114,17 @@ export default function EditNote(props) {
...
-            value={inputs.updated_at}
-            className={classes.textField}
-            InputLabelProps={{
-              shrink: true,
-            }}
+        <MuiPickersUtilsProvider utils={DateFnUtils}>
+          <DateTimePicker
+            className={classes.datePicker}
+            value={date}
+            onChange={e => setDate(e.target.value)}
```
Comment (harumhelmy) [inline src/frontend/components/utils/EditNote.jsx:124]: Same as in AddNote.jsx, I believe this should be `onChange={e => setDate(e)}`
